apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: v4train-tls-cert
spec:
  secretName: v4train-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "v4train.eastus.cloudapp.azure.com"